### ISSUE TITLE
Export certificates to be signed

### ISSUE THREAD

**Issue by stevelaskaridis** [grnet/access-ca-portal#83] opened 2015-11-22 12:39 UTC
## Description

An essential step before signing the certificates offline (issue #63) is to export the pending certificates. An API call and/or a relevant script should be implemented in order to achieve this functionality.

**Comment by NicolasLiampotis** [comment] 2015-11-23 14:42
Closing as duplicate of #48.

**Closed as completed by NicolasLiampotis** 2015-11-23 14:42 UTC
Labels: duplicate
